/*
 Navicat Premium Data Transfer

 Source Server         : localhost_docker_oracle
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : localhost:1522
 Source Schema         : SPRINGBOOTEASYCC

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 05/01/2021 20:05:28
*/


-- ----------------------------
-- Table structure for PROJECT_FILE
-- ----------------------------
DROP TABLE "SPRINGBOOTEASYCC"."PROJECT_FILE";
CREATE TABLE "SPRINGBOOTEASYCC"."PROJECT_FILE" (
  "ID" NUMBER NOT NULL ,
  "CREATE_TIME" DATE DEFAULT CURRENT_TIMESTAMP     ,
  "UPDATE_TIME" DATE ,
  "FILE_PATH" VARCHAR2(500 BYTE) NOT NULL ,
  "URL" VARCHAR2(500 BYTE) NOT NULL ,
  "FILENAME" VARCHAR2(500 BYTE) NOT NULL ,
  "TYPE" VARCHAR2(50 BYTE) ,
  "PK_VALUE" VARCHAR2(50 BYTE) ,
  "REMARK" VARCHAR2(500 BYTE) ,
  "BAN" NUMBER DEFAULT 0  ,
  "DELETED" NUMBER DEFAULT 0  ,
  "VERSION" NUMBER DEFAULT 0  ,
  "HANDLER_ID" NUMBER 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."PROJECT_FILE"."ID" IS '主键ID';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."PROJECT_FILE"."CREATE_TIME" IS '数据创建时间';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."PROJECT_FILE"."UPDATE_TIME" IS '数据修改时间';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."PROJECT_FILE"."FILE_PATH" IS '文件磁盘路径';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."PROJECT_FILE"."URL" IS '文件访问路径';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."PROJECT_FILE"."FILENAME" IS '文件名称';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."PROJECT_FILE"."TYPE" IS '文件类型';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."PROJECT_FILE"."PK_VALUE" IS '外键ID';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."PROJECT_FILE"."REMARK" IS '备注';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."PROJECT_FILE"."BAN" IS '是否停用';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."PROJECT_FILE"."DELETED" IS '是否删除';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."PROJECT_FILE"."VERSION" IS '版本号';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."PROJECT_FILE"."HANDLER_ID" IS '上传者';

-- ----------------------------
-- Records of PROJECT_FILE
-- ----------------------------
INSERT INTO "SPRINGBOOTEASYCC"."PROJECT_FILE" VALUES ('3', TO_DATE('2021-01-05 15:51:50', 'SYYYY-MM-DD HH24:MI:SS'), NULL, '/Users/wangxiaohui/dev-static/springboot-easycc/static/files/ESRemote/remoteExtDic.txt', 'http://10.101.70.43:7999/static/files/ESRemote/remoteExtDic.txt', 'remoteExtDic.txt', 'ES', NULL, NULL, '0', '1', '0', '1');
INSERT INTO "SPRINGBOOTEASYCC"."PROJECT_FILE" VALUES ('4', TO_DATE('2021-01-05 16:05:26', 'SYYYY-MM-DD HH24:MI:SS'), NULL, '/Users/wangxiaohui/dev-static/springboot-easycc/static/files/ESRemote/remoteExtDic.txt', 'http://10.101.70.43:7999/static/files/ESRemote/remoteExtDic.txt', 'remoteExtDic.txt', 'ES', NULL, NULL, '0', '1', '0', '1');
INSERT INTO "SPRINGBOOTEASYCC"."PROJECT_FILE" VALUES ('5', TO_DATE('2021-01-05 16:05:32', 'SYYYY-MM-DD HH24:MI:SS'), NULL, '/Users/wangxiaohui/dev-static/springboot-easycc/static/files/ESRemote/remoteBanDic.txt', 'http://10.101.70.43:7999/static/files/ESRemote/remoteBanDic.txt', 'remoteBanDic.txt', 'ES', NULL, NULL, '0', '1', '0', '1');
INSERT INTO "SPRINGBOOTEASYCC"."PROJECT_FILE" VALUES ('6', TO_DATE('2021-01-05 16:05:52', 'SYYYY-MM-DD HH24:MI:SS'), NULL, '/Users/wangxiaohui/dev-static/springboot-easycc/static/files/ESRemote/remoteExtDic.txt', 'http://10.101.70.43:7999/static/files/ESRemote/remoteExtDic.txt', 'remoteExtDic.txt', 'ES', NULL, NULL, '0', '1', '0', '1');
INSERT INTO "SPRINGBOOTEASYCC"."PROJECT_FILE" VALUES ('7', TO_DATE('2021-01-05 16:05:55', 'SYYYY-MM-DD HH24:MI:SS'), NULL, '/Users/wangxiaohui/dev-static/springboot-easycc/static/files/ESRemote/remoteBanDic.txt', 'http://10.101.70.43:7999/static/files/ESRemote/remoteBanDic.txt', 'remoteBanDic.txt', 'ES', NULL, NULL, '0', '1', '0', '1');
INSERT INTO "SPRINGBOOTEASYCC"."PROJECT_FILE" VALUES ('8', TO_DATE('2021-01-05 16:06:04', 'SYYYY-MM-DD HH24:MI:SS'), NULL, '/Users/wangxiaohui/dev-static/springboot-easycc/static/files/ESRemote/remoteExtDic.txt', 'http://10.101.70.43:7999/static/files/ESRemote/remoteExtDic.txt', 'remoteExtDic.txt', 'ES', NULL, NULL, '0', '1', '0', '1');
INSERT INTO "SPRINGBOOTEASYCC"."PROJECT_FILE" VALUES ('9', TO_DATE('2021-01-05 16:06:04', 'SYYYY-MM-DD HH24:MI:SS'), NULL, '/Users/wangxiaohui/dev-static/springboot-easycc/static/files/ESRemote/remoteBanDic.txt', 'http://10.101.70.43:7999/static/files/ESRemote/remoteBanDic.txt', 'remoteBanDic.txt', 'ES', NULL, NULL, '0', '1', '0', '1');
INSERT INTO "SPRINGBOOTEASYCC"."PROJECT_FILE" VALUES ('10', TO_DATE('2021-01-05 16:11:39', 'SYYYY-MM-DD HH24:MI:SS'), NULL, '/Users/wangxiaohui/dev-static/springboot-easycc/static/files/ESRemote/remoteExtDic.txt', 'http://10.101.70.43:7999/static/files/ESRemote/remoteExtDic.txt', 'remoteExtDic.txt', 'ES', NULL, NULL, '0', '1', '0', '1');
INSERT INTO "SPRINGBOOTEASYCC"."PROJECT_FILE" VALUES ('11', TO_DATE('2021-01-05 16:11:39', 'SYYYY-MM-DD HH24:MI:SS'), NULL, '/Users/wangxiaohui/dev-static/springboot-easycc/static/files/ESRemote/remoteBanDic.txt', 'http://10.101.70.43:7999/static/files/ESRemote/remoteBanDic.txt', 'remoteBanDic.txt', 'ES', NULL, NULL, '0', '1', '0', '1');
INSERT INTO "SPRINGBOOTEASYCC"."PROJECT_FILE" VALUES ('12', TO_DATE('2021-01-05 16:11:55', 'SYYYY-MM-DD HH24:MI:SS'), NULL, '/Users/wangxiaohui/dev-static/springboot-easycc/static/files/ESRemote/remoteExtDic.txt', 'http://10.101.70.43:7999/static/files/ESRemote/remoteExtDic.txt', 'remoteExtDic.txt', 'ES', NULL, NULL, '0', '1', '0', '1');
INSERT INTO "SPRINGBOOTEASYCC"."PROJECT_FILE" VALUES ('13', TO_DATE('2021-01-05 16:11:55', 'SYYYY-MM-DD HH24:MI:SS'), NULL, '/Users/wangxiaohui/dev-static/springboot-easycc/static/files/ESRemote/remoteBanDic.txt', 'http://10.101.70.43:7999/static/files/ESRemote/remoteBanDic.txt', 'remoteBanDic.txt', 'ES', NULL, NULL, '0', '1', '0', '1');
INSERT INTO "SPRINGBOOTEASYCC"."PROJECT_FILE" VALUES ('14', TO_DATE('2021-01-05 16:12:07', 'SYYYY-MM-DD HH24:MI:SS'), NULL, '/Users/wangxiaohui/dev-static/springboot-easycc/static/files/ESRemote/remoteExtDic.txt', 'http://10.101.70.43:7999/static/files/ESRemote/remoteExtDic.txt', 'remoteExtDic.txt', 'ES', NULL, NULL, '0', '1', '0', '1');
INSERT INTO "SPRINGBOOTEASYCC"."PROJECT_FILE" VALUES ('15', TO_DATE('2021-01-05 16:12:07', 'SYYYY-MM-DD HH24:MI:SS'), NULL, '/Users/wangxiaohui/dev-static/springboot-easycc/static/files/ESRemote/remoteBanDic.txt', 'http://10.101.70.43:7999/static/files/ESRemote/remoteBanDic.txt', 'remoteBanDic.txt', 'ES', NULL, NULL, '0', '1', '0', '1');
INSERT INTO "SPRINGBOOTEASYCC"."PROJECT_FILE" VALUES ('16', TO_DATE('2021-01-05 16:13:48', 'SYYYY-MM-DD HH24:MI:SS'), NULL, '/Users/wangxiaohui/dev-static/springboot-easycc/static/files/ESRemote/remoteExtDic.txt', 'http://10.101.70.43:7999/static/files/ESRemote/remoteExtDic.txt', 'remoteExtDic.txt', 'ES', NULL, NULL, '0', '0', '0', '1');
INSERT INTO "SPRINGBOOTEASYCC"."PROJECT_FILE" VALUES ('17', TO_DATE('2021-01-05 16:13:48', 'SYYYY-MM-DD HH24:MI:SS'), NULL, '/Users/wangxiaohui/dev-static/springboot-easycc/static/files/ESRemote/remoteBanDic.txt', 'http://10.101.70.43:7999/static/files/ESRemote/remoteBanDic.txt', 'remoteBanDic.txt', 'ES', NULL, NULL, '0', '0', '0', '1');
INSERT INTO "SPRINGBOOTEASYCC"."PROJECT_FILE" VALUES ('1', TO_DATE('2021-01-05 15:50:26', 'SYYYY-MM-DD HH24:MI:SS'), NULL, '/Users/wangxiaohui/dev-static/springboot-easycc/static/files/ESRemote/remoteExtDic.txt', 'http://10.101.70.43:7999/static/files/ESRemote/remoteExtDic.txt', 'remoteExtDic.txt', 'ES', NULL, NULL, '0', '1', '0', '1');
INSERT INTO "SPRINGBOOTEASYCC"."PROJECT_FILE" VALUES ('2', TO_DATE('2021-01-05 15:50:26', 'SYYYY-MM-DD HH24:MI:SS'), NULL, '/Users/wangxiaohui/dev-static/springboot-easycc/static/files/ESRemote/remoteBanDic.txt', 'http://10.101.70.43:7999/static/files/ESRemote/remoteBanDic.txt', 'remoteBanDic.txt', 'ES', NULL, NULL, '0', '1', '0', '1');
COMMIT;

-- ----------------------------
-- Table structure for SYS_USER
-- ----------------------------
DROP TABLE "SPRINGBOOTEASYCC"."SYS_USER";
CREATE TABLE "SPRINGBOOTEASYCC"."SYS_USER" (
  "ID" NUMBER(11) NOT NULL ,
  "CREATE_TIME" DATE DEFAULT CURRENT_TIMESTAMP      NOT NULL ,
  "ORGANIZATION_ID" NUMBER(11) NOT NULL ,
  "LOGIN_NAME" VARCHAR2(100 BYTE) NOT NULL ,
  "PASSWORD" VARCHAR2(100 BYTE) NOT NULL ,
  "USER_TYPE" NUMBER(11) ,
  "USERNAME" VARCHAR2(100 BYTE) ,
  "NICKNAME" VARCHAR2(100 BYTE) ,
  "GENDER" VARCHAR2(10 BYTE) ,
  "PHONE" VARCHAR2(30 BYTE) ,
  "TAX" VARCHAR2(30 BYTE) ,
  "MAIL" VARCHAR2(100 BYTE) ,
  "LOGIN_IP" VARCHAR2(100 BYTE) ,
  "LOGIN_TIME" DATE DEFAULT NULL ,
  "LOGIN_MAC" VARCHAR2(100 BYTE) ,
  "REMARK" CLOB ,
  "BAN" NUMBER(11) DEFAULT 1      NOT NULL ,
  "ID_CARD" VARCHAR2(30 BYTE) ,
  "JOB_CLASS" VARCHAR2(100 BYTE) ,
  "POST_STATUS" VARCHAR2(30 BYTE) ,
  "POST_CODE" VARCHAR2(30 BYTE) ,
  "POST_DESC" VARCHAR2(100 BYTE) ,
  "POST_CATEGORY" VARCHAR2(30 BYTE) ,
  "JOB_CODE" VARCHAR2(30 BYTE) ,
  "JOB_NAME" VARCHAR2(100 BYTE) ,
  "DEGREE" VARCHAR2(100 BYTE) ,
  "POLITICS_STATUS" VARCHAR2(30 BYTE) ,
  "WECHAT_ID" VARCHAR2(30 BYTE) ,
  "WECHAT_NAME" VARCHAR2(30 BYTE) ,
  "AVATAR" VARCHAR2(100 BYTE) ,
  "WORK_TIME" DATE ,
  "AM_CODE" VARCHAR2(30 BYTE) ,
  "ROLE_TYPE" VARCHAR2(100 BYTE) DEFAULT USER 
 
  ,
  "WECHAT_OPENID" VARCHAR2(255 BYTE) ,
  "UPDATE_TIME" DATE ,
  "DELETED" NUMBER(11) ,
  "VERSION" NUMBER 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."SYS_USER"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."SYS_USER"."ORGANIZATION_ID" IS '机构id';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."SYS_USER"."LOGIN_NAME" IS '登录名';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."SYS_USER"."PASSWORD" IS '登录密码';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."SYS_USER"."USERNAME" IS '真实姓名';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."SYS_USER"."NICKNAME" IS '昵称';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."SYS_USER"."GENDER" IS '性别';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."SYS_USER"."PHONE" IS '手机';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."SYS_USER"."TAX" IS '座机';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."SYS_USER"."MAIL" IS '邮箱';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."SYS_USER"."LOGIN_IP" IS '登录ip';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."SYS_USER"."LOGIN_TIME" IS '最后登录时间';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."SYS_USER"."LOGIN_MAC" IS 'mac地址';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."SYS_USER"."REMARK" IS '备注';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."SYS_USER"."BAN" IS '是否启用 0停用1启用';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."SYS_USER"."ID_CARD" IS '身份证号';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."SYS_USER"."JOB_CLASS" IS '职级';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."SYS_USER"."POST_STATUS" IS '岗位状态';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."SYS_USER"."POST_CODE" IS '岗位编码';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."SYS_USER"."POST_DESC" IS '岗位描述';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."SYS_USER"."POST_CATEGORY" IS '岗位类别';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."SYS_USER"."JOB_CODE" IS '职位编码';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."SYS_USER"."JOB_NAME" IS '职位名称';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."SYS_USER"."DEGREE" IS '学历';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."SYS_USER"."POLITICS_STATUS" IS '政治面貌';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."SYS_USER"."WECHAT_ID" IS '微信号';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."SYS_USER"."WECHAT_NAME" IS '微信昵称';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."SYS_USER"."AVATAR" IS '照片';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."SYS_USER"."WORK_TIME" IS '参加工作时间';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."SYS_USER"."AM_CODE" IS '即时通号';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."SYS_USER"."ROLE_TYPE" IS '用户角色';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."SYS_USER"."WECHAT_OPENID" IS '微信 openId';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."SYS_USER"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."SYS_USER"."DELETED" IS '是否禁用';
COMMENT ON COLUMN "SPRINGBOOTEASYCC"."SYS_USER"."VERSION" IS '版本号';

-- ----------------------------
-- Records of SYS_USER
-- ----------------------------
INSERT INTO "SPRINGBOOTEASYCC"."SYS_USER" VALUES ('1', TO_DATE('2021-01-04 12:07:07', 'SYYYY-MM-DD HH24:MI:SS'), '1', 'admin', '96e79218965eb72c92a549dd5a330112', '1', 'admin', NULL, NULL, NULL, NULL, NULL, '127.0.0.1', TO_DATE('2021-01-05 16:13:34', 'SYYYY-MM-DD HH24:MI:SS'), NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'SYSTEM', NULL, NULL, '0', NULL);
INSERT INTO "SPRINGBOOTEASYCC"."SYS_USER" VALUES ('591', TO_DATE('2021-01-04 12:14:39', 'SYYYY-MM-DD HH24:MI:SS'), '1', 'scyys1', '96e79218965eb72c92a549dd5a330112', '1', 'scyys1', NULL, NULL, NULL, NULL, NULL, '127.0.0.1', TO_DATE('2021-01-04 16:34:48', 'SYYYY-MM-DD HH24:MI:SS'), NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'POR', NULL, NULL, '0', NULL);
COMMIT;

-- ----------------------------
-- Sequence structure for SEQ_PROJECT_FILE
-- ----------------------------
DROP SEQUENCE "SPRINGBOOTEASYCC"."SEQ_PROJECT_FILE";
CREATE SEQUENCE "SPRINGBOOTEASYCC"."SEQ_PROJECT_FILE" MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Primary Key structure for table PROJECT_FILE
-- ----------------------------
ALTER TABLE "SPRINGBOOTEASYCC"."PROJECT_FILE" ADD CONSTRAINT "SYS_C0011960" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table PROJECT_FILE
-- ----------------------------
ALTER TABLE "SPRINGBOOTEASYCC"."PROJECT_FILE" ADD CONSTRAINT "SYS_C0011950" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."PROJECT_FILE" ADD CONSTRAINT "SYS_C0011952" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."PROJECT_FILE" ADD CONSTRAINT "SYS_C0011953" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."PROJECT_FILE" ADD CONSTRAINT "SYS_C0011954" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."PROJECT_FILE" ADD CONSTRAINT "SYS_C0011955" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."PROJECT_FILE" ADD CONSTRAINT "SYS_C0011956" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."PROJECT_FILE" ADD CONSTRAINT "SYS_C0011957" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."PROJECT_FILE" ADD CONSTRAINT "SYS_C0011958" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."PROJECT_FILE" ADD CONSTRAINT "SYS_C0011959" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."PROJECT_FILE" ADD CONSTRAINT "SYS_C0011961" CHECK ("FILE_PATH" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."PROJECT_FILE" ADD CONSTRAINT "SYS_C0011962" CHECK ("URL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."PROJECT_FILE" ADD CONSTRAINT "SYS_C0011963" CHECK ("FILENAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table SYS_USER
-- ----------------------------
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007796" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table SYS_USER
-- ----------------------------
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C0011687" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C0011688" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C0011689" CHECK ("ORGANIZATION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C0011690" CHECK ("LOGIN_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C0011691" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C0011692" CHECK ("BAN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C0011804" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C0011805" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C0011806" CHECK ("ORGANIZATION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C0011807" CHECK ("LOGIN_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C0011808" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C0011809" CHECK ("BAN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C0011865" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C0011866" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C0011867" CHECK ("ORGANIZATION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C0011868" CHECK ("LOGIN_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C0011869" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C0011870" CHECK ("BAN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007606" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007607" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007608" CHECK ("ORGANIZATION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007609" CHECK ("LOGIN_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007610" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007611" CHECK ("BAN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007754" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007755" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007756" CHECK ("ORGANIZATION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007757" CHECK ("LOGIN_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007758" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007759" CHECK ("BAN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007760" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007761" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007762" CHECK ("ORGANIZATION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007763" CHECK ("LOGIN_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007764" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007765" CHECK ("BAN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007766" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007767" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007768" CHECK ("ORGANIZATION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007769" CHECK ("LOGIN_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007770" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007771" CHECK ("BAN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007772" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007773" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007774" CHECK ("ORGANIZATION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007775" CHECK ("LOGIN_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007776" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007777" CHECK ("BAN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007778" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007779" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007780" CHECK ("ORGANIZATION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007781" CHECK ("LOGIN_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007782" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007783" CHECK ("BAN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007784" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007785" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007786" CHECK ("ORGANIZATION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007787" CHECK ("LOGIN_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007788" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007789" CHECK ("BAN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007790" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007791" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007792" CHECK ("ORGANIZATION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007793" CHECK ("LOGIN_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007794" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SPRINGBOOTEASYCC"."SYS_USER" ADD CONSTRAINT "SYS_C007795" CHECK ("BAN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
COMMIT;
